/* eslint-disable react/react-in-jsx-scope */
import { Inter } from "next/font/google";
import React from "react";
import Providers from "./Providers";

// eslint-disable-next-line no-unused-vars
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
